### ISSUE TITLE
UX feedback: inverted score is non-intuitive

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-old#8]
I am getting consistent feedback that the score (low being worse, high being good) does not work intuitively for "risks". People expect: high number == high risk.

So, I would recommend we change the inverted score to a normal score. 

This user experience was tested with IT security professionals as well as with people from completely different fields (social sciences). The feedback is consistent: the inverted score is confusing and counter intuitive when talking about "risks". If we were to talk about "goodie points per country" then a higher score would make sense to mean "good". But in our case it really is risks. High risk should be a higher score.

* [ ] change compute score
* [ ] change all the color scaling
* [ ] change default sort order
* [ ] change instructions on the about page

**Comment by rgrp** [comment]
Sounds sensible. It is quite easy to invert this and then switch the colour coding.

I assume we also want to switch ranks at the same time so "worst" country is "no 1". @aaronkaplan can you confirm that.

**Comment by aaronkaplan** [comment]
confirmed

**Comment by aaronkaplan** [comment]
---
Mobile

> On 12.06.2016, at 21:30, Rufus Pollock <notifications@github.com> wrote:
> 
> Sounds sensible. It is quite easy to invert this and then switch the colour coding.
> 
> I assume we also want to switch ranks at the same time so "worst" country is "no 1". @aaronkaplan can you confirm that.
> 

Confirmed.

**Comment by aaronkaplan** [comment]
regression in stats-new
